<?xml version="1.0"?>
<package format="3">
  <name>rmcs_local_map</name>
  <version>0.0.0</version>
  <description>Standalone RMCS obstacle local map package.</description>

  <maintainer email="dev@livoxtech.com">claydergc</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>livox_ros_driver2</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
